<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Rosetta store: simple mediation</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129366054-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129366054-1');
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">jAMM</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="glm.html">Docs</a>
</li>
<li>
  <a href="examples.html">Examples</a>
</li>
<li>
  <a href="rosetta.html">Rosetta store</a>
</li>
<li>
  <a href="release_notes.html">Release notes</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/jamovi-amm/jamm">View on Github</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Rosetta store: simple mediation</h1>

</div>


<p><span class="keywords"> <span class="keytitle"> keywords </span>
jamovi, SPSS, R, PROCESS, mediation </span></p>
<p><span class="version"> <span class="versiontitle"> jAMM version ≥
</span> 0.0.4 </span></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Here you can find comparisons of results obtained in jamovi jAMM,
jamovi (jmv), pure R, and SPSS. When not explicitly discussed, the code
of different software is written with the aim of obtaining equivalent
results across programs.</p>
</div>
<div id="simple-mediation" class="section level1">
<h1>Simple mediation</h1>
<p>Here we analyze the data discussed in the
<a href="glm_example1.html">jAMM: simple mediation</a>. Data can be
downloaded from <a
href="http://static.lib.virginia.edu/statlab/materials/data/mediationData.csv">University
of Virginia Research Data Service</a>. Here we renamed the
variables:</p>
<ul>
<li>grades = X</li>
<li>selfesteem = M</li>
<li>happiness = Y</li>
</ul>
<p>The mediation model is:</p>
<p><img src="examples/virginia_simple/pathdiagram.png" class="img-responsive" alt=""></p>
</div>
<div id="jamm" class="section level1">
<h1>jAMM</h1>
<p>As discussed in <a href="glm_example1.html">jAMM: simple
mediation</a>, jAMM estimation and standard statistical tests are:</p>
<p><img src="examples/virginia_simple/results1.png" class="img-responsive" alt=""></p>
<p>The bootstrap confidence intervals (bias-corrected and accelerated)
and z-tests are:</p>
<p><img src="examples/virginia_simple/results2.png" class="img-responsive" alt=""></p>
</div>
<div id="r-lm" class="section level1">
<h1>R lm()</h1>
<p>Estimation of the regression coefficients can be obtained in vanilla
R with two linear regressions:</p>
<pre class="r"><code>data&lt;-read.csv(&#39;../data/virginia_simple_mediation.csv&#39;)

mod1&lt;-lm(selfesteem~grades,data=data)
summary(mod1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = selfesteem ~ grades, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.3046 -0.8656  0.1344  1.1344  4.6954 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.49952    0.58920   2.545   0.0125 *  
## grades       0.56102    0.09448   5.938 4.39e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.639 on 98 degrees of freedom
## Multiple R-squared:  0.2646, Adjusted R-squared:  0.2571 
## F-statistic: 35.26 on 1 and 98 DF,  p-value: 4.391e-08</code></pre>
<pre class="r"><code>mod2&lt;-lm(hapiness~selfesteem+grades,data=data)
summary(mod2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = hapiness ~ selfesteem + grades, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.7631 -1.2393  0.0308  1.0832  4.0055 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.9043     0.6055   3.145   0.0022 ** 
## selfesteem    0.6355     0.1005   6.321 7.92e-09 ***
## grades        0.0396     0.1096   0.361   0.7187    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.631 on 97 degrees of freedom
## Multiple R-squared:  0.373,  Adjusted R-squared:  0.3601 
## F-statistic: 28.85 on 2 and 97 DF,  p-value: 1.471e-10</code></pre>
<p>by multiplying 0.561 and 0.6355, one obtains the mediated effect
0.3565, as in jAMM. We can notice that the t-tests in R are slightly
different from the z-tests in jAMM. This is simply due to the
computation of the standard errors. jAMM is based on
<code>R lavaan package</code>, that uses the <a
href="http://lavaan.ugent.be/tutorial/est.html">expected information
matrix</a> obtain the standard errors.</p>
</div>
<div id="c.i.-with-rmediation-package" class="section level1">
<h1>C.I. with Rmediation package</h1>
<p>In R, simple mediation models confidence intervals can be computed
with <a
href="https://cran.r-project.org/web/packages/RMediation/RMediation.pdf">the
Rmediation package</a>, which provides several methods of
computation.</p>
<pre class="r"><code>library(RMediation,quietly = T)</code></pre>
<pre><code>## This is lavaan 0.6-17
## lavaan is FREE software! Please report any bugs.</code></pre>
<pre><code>## To take full advantage of multiple cores, use:
##   mxOption(key=&#39;Number of Threads&#39;, value=parallel::detectCores()) #now
##   Sys.setenv(OMP_NUM_THREADS=parallel::detectCores()) #before library(OpenMx)</code></pre>
<pre><code>## 
## Attaching package: &#39;OpenMx&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:Matrix&#39;:
## 
##     %&amp;%, expm</code></pre>
<pre class="r"><code>sumr1&lt;-summary(mod1)
sumr2&lt;-summary(mod2)
a&lt;-sumr1$coefficients[2,1]
se.a&lt;-sumr1$coefficients[2,2]
b&lt;-sumr2$coefficients[2,1]
se.b&lt;-sumr2$coefficients[2,2]

#### delta method #####
medci(a, b, se.a, se.b,type = &quot;asymp&quot;)[1]</code></pre>
<pre><code>## $`95% CI`
## [1] 0.1939949 0.5190495</code></pre>
<pre class="r"><code>#### Monte Carlo method ####
medci(a, b, se.a, se.b,type = &quot;MC&quot;)[1]</code></pre>
<pre><code>## $`95% CI`
##      2.5%     97.5% 
## 0.2076877 0.5308750</code></pre>
<p>In R, simple bootstrap confidence intervals can be computed with <a
href="https://cran.r-project.org/web/packages/mediation/mediation.pdf">the
mediation package</a></p>
<p>Here are the results, again in line with the jAMM results.</p>
<pre class="r"><code>library(mediation,quietly = T)

med&lt;-mediate(mod1, mod2, treat=&#39;grades&#39;, mediator=&#39;selfesteem&#39;, sims=1000, boot = T, boot.ci.type = &quot;bca&quot;)</code></pre>
<pre><code>## Running nonparametric bootstrap</code></pre>
<pre class="r"><code>summary(med)</code></pre>
<pre><code>## 
## Causal Mediation Analysis 
## 
## Nonparametric Bootstrap Confidence Intervals with the BCa Method
## 
##                Estimate 95% CI Lower 95% CI Upper p-value    
## ACME             0.3565       0.2232         0.53  &lt;2e-16 ***
## ADE              0.0396      -0.1907         0.30    0.73    
## Total Effect     0.3961       0.1668         0.64  &lt;2e-16 ***
## Prop. Mediated   0.9000       0.5903         2.80  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Sample Size Used: 100 
## 
## 
## Simulations: 1000</code></pre>
</div>
<div id="spss-process" class="section level1">
<h1>SPSS Process</h1>
<p>In spss, one can estimate simple mediation and get confidence
intervals for mediated effect using <a
href="http://www.processmacro.org/download.html">PROCESS macro</a>. The
results coincide with the jAMM results.</p>
<p><img src="rosetta/virginia_simple/process.png" class="img-responsive" alt=""></p>
<p>Recall that PROCESS uses the “percentile” method for bootstrap
confidence intervals, thus, to get an even closer match between PROCESS
and jAMM, one can ask jAMM to use this method as well. Here are the
results, which align to PROCESS results to the second significant
digit.</p>
<p><img src="rosetta/virginia_simple/ci_percent.png" class="img-responsive" alt=""></p>
<p>Notice that the “Completely standardized indirect effect” in PROCESS
corresponds to jAMM <span class="math inline">\(beta\)</span> effect,
which is, as the name signals, the mediated effect obtained after
standardizing all variables.</p>
</div>
<div id="rosettas-files" class="section level1">
<h1>Rosetta’s files</h1>
<ul>
<li>
<a href="rosetta_moderation.html">Rosetta store: conditional
mediation</a>
</li>
<li>
<a href="rosetta_simple.html">Rosetta store: simple mediation</a>
</li>
</ul>
<h1>
Comments?
</h1>
<p>
Got comments, issues or spotted a bug? Please open an issue on
<a href=" https://github.com/mcfanda/gamlj/issues "> GAMLj at
github“</a> or <a href="mailto:mcfanda@gmail.com">send me an email</a>
</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
