---
title: "covariateScaling_chunk"
output: html_document
---


`Covariates conditioning` rules how the model is conditioned to different values of the continuous independent variables when one or more moderators are defined.

* `Mean+SD`: means that the IV is conditioned to the $mean$,  to $mean+k \cdot sd$, and to  $mean-k\cdot sd$, where $k$ is ruled by the white field below the option. Default is 1 SD.

* `Percentile 50 +offset`: means that the IV is conditioned to the $median$, the  $median+k P$, and the $median-k\cdot P$, where $P$ is the offset of percentile one needs. Again, the $P$ is ruled by the white field below the option. Default is 25%. The default conditions the model to: 

    + $50^{th}-25^{th}=25^{th}$ percentile
    
    + $50^{th}$ percentile 
    
    + $50^{th}+25^{th}=75^{th}$ percentile 

The offset should be within 5 and 50.

`Covariates labeling` decides which label should be associated with the estimates and table titles:

* `Labels` produces strings of the form $Mean \pm SD$

* `Values` uses the actual values of the variables

* `Labels+Values` produces labels of the form $Mean \pm SD=XXXX$, where `XXXX` is the actual value.

